services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db: